services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gestion_listas_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - springboot-mysql-network
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: gestion_listas_db
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - springboot-mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "db" ]
      retries: 10
      interval: 5s
      timeout: 30s
networks:
  springboot-mysql-network:
    name: springboot-mysql-network